/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClickupEvents": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ClickupToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyLinkable": {
      "foo": string
      "type": "sst.sst.Linkable"
    }
  }
}
