/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClickupEvents": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ClickupToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyPostgres": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Postgres"
      "username": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
